openapi: 3.0.3
info:
  title: ZipDuck OAuth 2.0 API
  description: Google, Kakao 소셜 로그인 API
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local development
  - url: https://api.zipduck.com/api/v1
    description: Production

tags:
  - name: OAuth
    description: 소셜 로그인

paths:
  /oauth2/authorize/{provider}:
    get:
      tags:
        - OAuth
      summary: OAuth 2.0 인증 시작
      description: Google 또는 Kakao OAuth 인증 페이지로 리다이렉트
      operationId: authorizeOAuth
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
            enum: [google, kakao]
          description: OAuth 제공자
      responses:
        '302':
          description: OAuth 제공자 인증 페이지로 리다이렉트
          headers:
            Location:
              schema:
                type: string
                example: https://accounts.google.com/o/oauth2/v2/auth?client_id=...

  /oauth2/callback/{provider}:
    get:
      tags:
        - OAuth
      summary: OAuth 2.0 콜백 처리
      description: OAuth 제공자로부터 인증 코드를 받아 사용자 정보 조회 및 토큰 발급
      operationId: oauthCallback
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
            enum: [google, kakao]
        - name: code
          in: query
          required: true
          schema:
            type: string
          description: OAuth 제공자가 발급한 인증 코드
        - name: state
          in: query
          schema:
            type: string
          description: CSRF 방지용 state 파라미터
      responses:
        '200':
          description: 신규 사용자 - 계정 생성 및 로그인 성공
          headers:
            Set-Cookie:
              description: Refresh Token
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '303':
          description: 기존 이메일 계정 존재 - 계정 연동 확인 필요
          headers:
            Location:
              schema:
                type: string
                example: /oauth2/link?token={tempToken}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkRequiredResponse'
        '400':
          description: OAuth 인증 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /oauth2/link:
    post:
      tags:
        - OAuth
      summary: 소셜 계정 연동
      description: 기존 이메일 계정과 소셜 로그인 계정 연동
      operationId: linkOAuthAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinkAccountRequest'
      responses:
        '200':
          description: 계정 연동 성공 및 로그인
          headers:
            Set-Cookie:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: 유효하지 않은 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
        tokenType:
          type: string
          enum: [Bearer]
        expiresIn:
          type: integer
        user:
          $ref: '#/components/schemas/UserResponse'

    LinkRequiredResponse:
      type: object
      properties:
        message:
          type: string
          example: 이미 가입된 이메일입니다. 기존 계정과 연동하시겠습니까?
        tempToken:
          type: string
          description: 계정 연동용 임시 토큰 (5분 유효)
          example: temp_abc123...
        existingProvider:
          type: string
          enum: [LOCAL, GOOGLE, KAKAO]
          example: LOCAL
        newProvider:
          type: string
          enum: [GOOGLE, KAKAO]
          example: GOOGLE

    LinkAccountRequest:
      type: object
      required:
        - tempToken
        - confirm
      properties:
        tempToken:
          type: string
          description: 콜백에서 받은 임시 토큰
        confirm:
          type: boolean
          description: 연동 확인 (true=연동, false=취소)
          example: true

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        username:
          type: string
        provider:
          type: string
          enum: [LOCAL, GOOGLE, KAKAO]
        status:
          type: string
        createdAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: object
